blueprint:
  name: Homematic 6-Key Remote Controller
  domain: automation
  input:
    button_1:
      name: Button 1 Event Entity
      selector:
        entity:
          domain: event
    button_2:
      name: Button 2 Event Entity
      selector:
        entity:
          domain: event
    button_3:
      name: Button 3 Event Entity
      selector:
        entity:
          domain: event
    button_4:
      name: Button 4 Event Entity
      selector:
        entity:
          domain: event
    button_5:
      name: Button 5 Event Entity
      selector:
        entity:
          domain: event
    button_6:
      name: Button 6 Event Entity
      selector:
        entity:
          domain: event

    action_button1_short:
      name: Button 1 Short Press
      default: []
      selector:
        action: {}
    action_button1_long:
      name: Button 1 Long Press
      default: []
      selector:
        action: {}
    action_button2_short:
      name: Button 2 Short Press
      default: []
      selector:
        action: {}
    action_button2_long:
      name: Button 2 Long Press
      default: []
      selector:
        action: {}
    action_button3_short:
      name: Button 3 Short Press
      default: []
      selector:
        action: {}
    action_button3_long:
      name: Button 3 Long Press
      default: []
      selector:
        action: {}
    action_button4_short:
      name: Button 4 Short Press
      default: []
      selector:
        action: {}
    action_button4_long:
      name: Button 4 Long Press
      default: []
      selector:
        action: {}
    action_button5_short:
      name: Button 5 Short Press
      default: []
      selector:
        action: {}
    action_button5_long:
      name: Button 5 Long Press
      default: []
      selector:
        action: {}
    action_button6_short:
      name: Button 6 Short Press
      default: []
      selector:
        action: {}
    action_button6_long:
      name: Button 6 Long Press
      default: []
      selector:
        action: {}

triggers:
  - trigger: event.received
    target:
      entity_id: !input button_1
    options:
      event_type: [press_short]
    id: b1_short
  - trigger: event.received
    target:
      entity_id: !input button_1
    options:
      event_type: [press_long]
    id: b1_long
  - trigger: event.received
    target:
      entity_id: !input button_2
    options:
      event_type: [press_short]
    id: b2_short
  - trigger: event.received
    target:
      entity_id: !input button_2
    options:
      event_type: [press_long]
    id: b2_long
  - trigger: event.received
    target:
      entity_id: !input button_3
    options:
      event_type: [press_short]
    id: b3_short
  - trigger: event.received
    target:
      entity_id: !input button_3
    options:
      event_type: [press_long]
    id: b3_long
  - trigger: event.received
    target:
      entity_id: !input button_4
    options:
      event_type: [press_short]
    id: b4_short
  - trigger: event.received
    target:
      entity_id: !input button_4
    options:
      event_type: [press_long]
    id: b4_long
  - trigger: event.received
    target:
      entity_id: !input button_5
    options:
      event_type: [press_short]
    id: b5_short
  - trigger: event.received
    target:
      entity_id: !input button_5
    options:
      event_type: [press_long]
    id: b5_long
  - trigger: event.received
    target:
      entity_id: !input button_6
    options:
      event_type: [press_short]
    id: b6_short
  - trigger: event.received
    target:
      entity_id: !input button_6
    options:
      event_type: [press_long]
    id: b6_long

conditions: []

actions:
  - choose:
      - conditions: "{{ trigger.id == 'b1_short' }}"
        sequence: !input action_button1_short
      - conditions: "{{ trigger.id == 'b1_long' }}"
        sequence: !input action_button1_long
      - conditions: "{{ trigger.id == 'b2_short' }}"
        sequence: !input action_button2_short
      - conditions: "{{ trigger.id == 'b2_long' }}"
        sequence: !input action_button2_long
      - conditions: "{{ trigger.id == 'b3_short' }}"
        sequence: !input action_button3_short
      - conditions: "{{ trigger.id == 'b3_long' }}"
        sequence: !input action_button3_long
      - conditions: "{{ trigger.id == 'b4_short' }}"
        sequence: !input action_button4_short
      - conditions: "{{ trigger.id == 'b4_long' }}"
        sequence: !input action_button4_long
      - conditions: "{{ trigger.id == 'b5_short' }}"
        sequence: !input action_button5_short
      - conditions: "{{ trigger.id == 'b5_long' }}"
        sequence: !input action_button5_long
      - conditions: "{{ trigger.id == 'b6_short' }}"
        sequence: !input action_button6_short
      - conditions: "{{ trigger.id == 'b6_long' }}"
        sequence: !input action_button6_long
mode: single