blueprint:
  name: Automatic Irrigation
  domain: automation
  input:
    valve:
      name: Valve
      description: The valve to control.
      selector:
        entity:
          domain: valve

    time_morning:
      name: Morning
      description: The time to start watering in the morning.
      selector:
        time:

    time_evening:
      name: Evening
      description: The time to start watering in the evening.
      selector:
        time:

    watering_duration:
      name: Watering Duration
      description: The duration to water the garden.
      default: 10
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

trigger:
  - platform: time
    at: !input time_morning
  - platform: time
    at: !input time_evening

action:
  - action: valve.open_valve
    entity_id: !input valve
