blueprint:
  name: Homematic HmIP-BSM Controller
  domain: automation
  input:
    button_top:
      name: Top Button Event Entity
      selector:
        entity:
          domain: event
    button_bottom:
      name: Bottom Button Event Entity
      selector:
        entity:
          domain: event
    action_top_short:
      name: Top Button Short Press
      default: []
      selector:
        action: {}
    action_top_long:
      name: Top Button Long Press
      default: []
      selector:
        action: {}
    action_bottom_short:
      name: Bottom Button Short Press
      default: []
      selector:
        action: {}
    action_bottom_long:
      name: Bottom Button Long Press
      default: []
      selector:
        action: {}

triggers:
  - trigger: event.received
    target:
      entity_id: !input button_top
    options:
      event_type:
        - press_short
    id: top_short
  - trigger: event.received
    target:
      entity_id: !input button_top
    options:
      event_type:
        - press_long
    id: top_long
  - trigger: event.received
    target:
      entity_id: !input button_bottom
    options:
      event_type:
        - press_short
    id: bottom_short
  - trigger: event.received
    target:
      entity_id: !input button_bottom
    options:
      event_type:
        - press_long
    id: bottom_long

conditions: []

actions:
  - choose:
      - conditions: "{{ trigger.id == 'top_short' }}"
        sequence: !input action_top_short
      - conditions: "{{ trigger.id == 'top_long' }}"
        sequence: !input action_top_long
      - conditions: "{{ trigger.id == 'bottom_short' }}"
        sequence: !input action_bottom_short
      - conditions: "{{ trigger.id == 'bottom_long' }}"
        sequence: !input action_bottom_long
mode: single